export enum FOLDER_NAMES {
  IMAGE = "image",
  SEATING_PLAN = "seatingPlan",
  BUSINESSPROFILEIMAGE = "businessProfileImage",
  GALLERY = "gallery",
  PROFILE_IMAGE = "profileImage",
  NID_FRONT_PIC = "nidFrontPic",
  CAR_REGISTRATION_PAPER_FRONT_PIC = "carRegistrationPaperFrontPic",
  CAR_REGISTRATION_PAPER_BACK_PIC = "carRegistrationPaperBackPic",
  NID_BACK_PIC = "nidBackPic",
  DRIVING_LICENSE_FRONT_PIC = "drivingLicenseFrontPic",
  DRIVING_LICENSE_BACK_PIC = "drivingLicenseBackPic",
  CHILD_IMAGE = "childImage",
  IMAGES = "images",
  LICENSE = "license",
  DRIVER_LICENSE = "driverLicense",
  INSURANCE = "insurance",
  PERMITS = "permits",
  BANNER = "banner",
  LOGO = "logo",
  AUDIO = "audio",
  VIDEO = "video",
  DOCUMENT = "document",
  THUMBNAIL = "thumbnail",
  OTHERS = "others",
  REMOVE_IMAGE = "removeImage",
}
